### ISSUE TITLE
Silverstripe 5 support?

### ISSUE THREAD

**Issue by elliot-sawyer** [pstaender/silverstripe-redis-cache#5]
Hey mate, this module is wonderful, it makes all of my Silverstripe installs incredibly fast and responsive! Have you given much thought to upgrading to Silverstripe 5 yet? I had a go at it over the weekend, but the underlying `symfony/cache` layer utilised by SS4 appears to have been deprecated and replaced with something new. 

Happy to help as I use this module a lot, just not sure where to begin!

**Comment by pstaender** [comment]
Hi @elliot-sawyer , glad you like it :) And thanks for already investigating in the upcoming SilverStripe upgrade and opening an issue.

My current situation is, that I no longer use SilverStripe (it may change in future, but for now I only mantain legacy projects). None of those is using redis for caching (just the slow file caching because there neither high-frequently-visited-sites nor running on pods). That means I'm not actually using the module myself… This is why I believe I won't upgrade it myself to SilverStripe 5 in near future.

So I would be happy if you (or anyone who is interested in) could investigate the steps for SS5 and write here or open a PR. We can make as SS5 branch for that of course.

**Comment by elliot-sawyer** [comment]
No worries mate, I can take a look at it!

**Comment by pstaender** [comment]
@elliot-sawyer I just published it as new version, I guess it should be fine and work under v4 + v5 now
